### ISSUE TITLE
cdk-serverless can not deploy

### ISSUE THREAD

**Issue by koilgg** [aws-samples/amazon-s3-resumable-upload#10]
您好，我希望部署serverless版本的amazon-s3-resumable-upload，但是在deploy cdk的时候出现了一些问题，想请教一下。

以下是我app.py的一些配置信息

```bash
# Define bucket and prefix for Jobsender to compare
bucket_para = [{
    "src_bucket": "jp-bucket",
    "src_prefix": "",
    "des_bucket": "cn-bucket",
    "des_prefix": ""
}]
StorageClass = 'STANDARD'

# Des_bucket_default is only used for non-jobsender use case, S3 trigger SQS then to Lambda.
# There is no destination buckets information in SQS message in this case, so you need to setup Des_bucket_default
Des_bucket_default = 'cn-bucket'
Des_prefix_default = 'test-dir'

JobType = 'PUT'
#我的ec2，lambda都将使用日本的账号
# 'PUT': Destination Bucket is not the same account as Lambda.
# 'GET': Source bucket is not the same account as Lambda.

JobsenderCompareVersionId = 'True'  # Jobsender should compare versioinId of source B3 bucket and versionId in DDB
UpdateVersionId = 'False'  # get lastest version id from s3 before before get object
GetObjectWithVersionId = 'True'  # get object together with the specified version id
```

然后我也配置了parameter store的信息

![image](https://user-images.githubusercontent.com/32815409/89852371-491c8b80-dbc1-11ea-9ff7-bfe72ac052f0.png)

在配置好这些之后，我也使用aws configure配置了我的ec2，并安装好了cdk，版本是：

```
1.57.0 (build 2ccfc50)
```

之后安装了requirements.txt的依赖环境，并使用

```
cdk synth
```
和
```
cdk deploy
```

但是后者在执行时会一直卡顿在那里，不能成功，想咨询一下是什么原因呢?

![image](https://user-images.githubusercontent.com/32815409/89852851-5e45ea00-dbc2-11ea-8dee-9754f9ff9181.png)

谢谢！

**Comment by huangzbaws** [comment]
如果第一次在这个region运行cdk，需要先运行cdk init执行初始化，这样它才会创建一个cdk的S3 bucket来放部署的代码，以便后续cloudformation去部署template

**Comment by koilgg** [comment]
谢谢您的提示，我按照您所说的重新进行了部署，但是在执行命令

`
cdk bootstrap
`

或者

`
cdk deploy
`
的时候，等待很长的时间仍然没有结果（30min以上）

请问是由于serverless的部署本身就需要大量的时间吗？

**Comment by huangzbaws** [comment]
有检查过网络么？bootstrap一般只需要一两分钟，而且bootstrap的过程跟代码无关的。
这个系统整个部署也就10来分钟。已经有大量用户部署过。

**Comment by huangzbaws** [comment]
可以先看看aws文档，部署一个最简单的样例cdk尝试一下
https://docs.aws.amazon.com/cdk/latest/guide/home.html
