### ISSUE TITLE
3T数据从OSS同步S3，有没有办法可以提速？5个小时内完成同步

### ISSUE THREAD

**Issue by lilywang2017** [aws-samples/amazon-s3-resumable-upload#11]
您好，

只有Single模式支持OSS为数据源.

AWS测试EC2配置： m5a.xlarge 
测试时间：                10分钟
同步到S3的结果：    11736 个对象, 1.2GB
修改s3_upload_config.ini配置项：MaxThread = 10 ，MaxParallelFile = 10

推算一个小时能同步7GB左右，3T数据需要同步42天。

准备同步的OSS文件结构可以分为6种前缀，我可开6台机器分前缀传输。理论7天左右能完成同步。

如题，如果我想5个小时左右完成同步，是否有办法？大神请指点，谢谢！

**Comment by bnusunny** [comment]
有没有看看rclone？ https://rclone.org/

**Comment by RealJaJaAdmin** [comment]
> 有没有看看rclone？ https://rclone.org/

我也试了下，2M/S的同步，还是慢。 OSS 和 S3 都开启加速传输，速度没明显提升

有办法提速吗？ 谢谢

**Comment by bnusunny** [comment]
源端和目地端分别是在什么地方呢？

**Comment by hawkey999** [comment]
按我的经验，这个的带宽瓶颈是在OSS的对外带宽限制上。
另外，Single模式，可以考虑分多个Single的VM来运行迁移不同的子目录。

**Comment by RealJaJaAdmin** [comment]
> 源端和目地端分别是在什么地方呢？

源端：阿里云美西
目的端：亚马逊美东 

我加大了并行传输的文件数量，目前16M/S。  ：） 还是觉得不够快

**Comment by RealJaJaAdmin** [comment]
> 按我的经验，这个的带宽瓶颈是在OSS的对外带宽限制上。
> 另外，Single模式，可以考虑分多个Single的VM来运行迁移不同的子目录。

我们的目录，不均匀分布。个别大的文件夹里我找找规律，也做下拆分试试。

谢谢 ：）

**Comment by zxkane** [comment]
> 您好，
> 
> 只有Single模式支持OSS为数据源.
> 
> AWS测试EC2配置： m5a.xlarge
> 测试时间： 10分钟
> 同步到S3的结果： 11736 个对象, 1.2GB
> 修改s3_upload_config.ini配置项：MaxThread = 10 ，MaxParallelFile = 10
> 
> 推算一个小时能同步7GB左右，3T数据需要同步42天。
> 
> 准备同步的OSS文件结构可以分为6种前缀，我可开6台机器分前缀传输。理论7天左右能完成同步。
> 
> 如题，如果我想5个小时左右完成同步，是否有办法？大神请指点，谢谢！

`xlarge` 网络性能是 up to 10Gb(是短时间可以突增到10Gb/s), 长时间大流量会被限制到3,4Gb/s(各region实测为准)，通过cloudwatch metrics可以查看实例网络吞吐是否已到瓶颈。

**Comment by JoeShi** [comment]
可以尝试一下 https://github.com/awslabs/aws-data-replication-hub, 在使用之前可以通过 AWS Support 提升 Lambda 的并发（默认是1000， 可以提升到5000 或者10000），这个方案底层的传输基于 Lambda, 是一个并行传输的方案。
