### ISSUE TITLE
ListMultipartUploads  AccessDenied

### ISSUE THREAD

**Issue by huangchaoqun** [aws-samples/amazon-s3-resumable-upload#13]
win10 
报错ClientError('An error occurred (AccessDenied) when calling the ListMultipartUploads operation: Access Denied')
按网上的帖子  对应的仓库路径下权限已经全开了  
用命令 执行没有报错
aws s3api list-multipart-uploads -bucket xxxxxx --prefix xxxxxxx 
把get_uploaded_list 注释了 可以正常上传文件

**Comment by hawkey999** [comment]
注释了get_uploaded_list会导致无法断点续传，每次中断之后都从头开始
还是应该排查清楚权限配置问题，检查源和目的两个Bucket的权限

**Comment by huangchaoqun** [comment]
![image](https://user-images.githubusercontent.com/24500684/92387466-29d53780-f148-11ea-8c31-0274971a0a8c.png)
这样设置权限应该都开放了  我是执行 amazon-s3-resumable-upload\single_node\s3_upload.py这个文件 报错的  源文件是本地文件  目标存储库已经按上面的截图配置了权限  能提供下您项目中配置的权限示例吗

**Comment by huangchaoqun** [comment]
权限问题
