### ISSUE TITLE
Windows下传输完成之后，出现WARING - There are xx files not in destination or not the sam size

### ISSUE THREAD

**Issue by sunl** [aws-samples/amazon-s3-resumable-upload#21]
传输完成之后，会把本地目录和S3上目录下的文件再做一次比较，如果源目录包含子目录，并且用的是Windows系统，会出现WARING - There are xx files not in destination or not the sam size, List:

![20230314152230](https://user-images.githubusercontent.com/4168127/224925622-c57e0e96-16cd-466b-93ba-9f17ff472c40.png)

原因是Windows系统下本地文件路径有2个斜杠\\，然后S3上的文件路径是一个斜杠/，不一致
目前简单通过如下方式解决：
![20230314152415](https://user-images.githubusercontent.com/4168127/224925774-086b0ae8-dd61-43c2-a4b8-2af983339129.png)

**Comment by huangzbaws** [comment]
Fixed compare_local_to_s3() to adapt windows path with:
source_file["Key"] = str(PurePosixPath(source_file["Key"]))
