### ISSUE TITLE
get  error when run too many tasks

### ISSUE THREAD

**Issue by orangeSi** [aws-samples/amazon-s3-resumable-upload#24]
If I run many ```s3trans``` tasks at one time, then some tasks will output error:
 ```
2024/01/05 10:10:08 Failed to read from response body: bucketname xxx/yyy.gz 33 unexpected EOF
2024/01/05 10:15:47 Failed to read from response body: bucketname xxx/yyy.gz 44 net/http: request canceled (Client.Timeout or context cancellation while reading body)
```
and the final output gz file is not completed.

But if I only run one ```s3trans``` task at one time, it will not ouput error and get the completed gz file.

So how to resove the error?  my command is ```s3trans  -y -l -n 4  --max-retries 30 --http-timeout 500```

thanks~
Si

**Comment by hawkey999** [comment]
It seems some request got timeout, try to use a higher cpu/mem compute, or try to config with less s3trans task or less num-workers.

E.g. s3trans  -y -l -n 2  --max-retries 30 --http-timeout 500
