### ISSUE TITLE
pre signed S3 url  download usage help

### ISSUE THREAD

**Issue by kedbirhan** [aws-samples/amazon-s3-resumable-upload#25]
Hi, i wanted to use this tool to download files  where I am given a pre-signed S3 URL of the file  and I want to download it to an S3 bucket I own. will i be able to do that,  if so example command I would run would be appreciated?

itried ./s3trans $url /Users/ec2User/dev/open-sources/amazon-s3-resumable-upload/ouput/
but it exits with error  
Failed to create directories: {the url variable}

**Comment by hawkey999** [comment]
It doesn't support presign url download in this version. Will it put into roadmap.

**Comment by huangzbaws** [comment]
Supported download from s3 presign url
