### ISSUE TITLE
Serverless 版本部署完毕后会立即启动 jobsender么？还是必须等待一个小时之后

### ISSUE THREAD

**Issue by JoeShi** [aws-samples/amazon-s3-resumable-upload#4]
目前的观察是不会，希望cdk 部署完之后能立即启动jobsender 传输现有文件

**Comment by huangzbaws** [comment]
Limit by AWS CloudWatch Rule feature:
本项目是创建了CloudWatch Rule去定时触发，创建以后CloudWatch并不立刻触发，而是等定时任务到时间做的触发。

**Comment by huangzbaws** [comment]
客户可以根据自己需求，在任何时候手工触发Jobsender Lambda function

**Comment by pahud** [comment]
可以用custom-resource寫一個資源，這個資源去觸發這個job

然後這個資源放最後再執行，這樣CDK一deploy完成，就會run job once

**Comment by JoeShi** [comment]
如何确保是这个资源是最后一个被执行的，CDK 里面有写 CloudFormation的 dependson 比较方便的方式么

**Comment by pahud** [comment]
> 如何确保是这个资源是最后一个被执行的，CDK 里面有写 CloudFormation的 dependson 比较方便的方式么


YES!

// resourceFoo depends on resourceBar

```ts
resourceFoo.node.addDependency(resourceBar)
```

if we need a custom resource as a trigger to kickoff the pipeline we simply:

```ts
const cr = new AwsCustomResource({...})
// or
const cr = new CustomResource({...})
// add ensure the dependency
cr.node.addDependency(myPipeline, anotherResource...)
```

In this case the custom resource will be created after `myPipeline` and `anotherResource`

**Comment by JoeShi** [comment]
借楼提问，

`cdk deploy` 的时候如何 disable rollback..  希望能够查看创建出来的资源方便调试。

**Comment by pahud** [comment]
> 借楼提问，
> 
> `cdk deploy` 的时候如何 disable rollback.. 希望能够查看创建出来的资源方便调试。

很多人想要，可惜還不行

https://github.com/aws/aws-cdk/issues/2562

**Comment by huangzbaws** [comment]
这个CDK加个dependency也是比较简单的：
加一个CustomResource指向 handler_jobsender
然后指定这个 CustomResource depends on sqs_queue

我发现我已经没有了这个repo的权限了，连setting都看不到了，以后就靠你们了。
