### ISSUE TITLE
S3 Object Metadata has been changed

### ISSUE THREAD

**Issue by JoeShi** [aws-samples/amazon-s3-resumable-upload#5]
Version: Serverless

I have images in the src bucket which has S3 Object Metadata value  `Content-Type = image/png`.

After it has been replicated to dest bucket, the Metadata has been change to `binary/octet-stream`. 

This will cause the browser to download the image instead of rendering.

**Comment by huangzbaws** [comment]
Current version has not handle metadata, need to enhance to get the original metadata and change the upload module with it

**Comment by huangzbaws** [comment]
Be noticed that:
AWS S3 API ListObject doesn't support list meta data, so if you need to get metadata, you have to get it one object by object by a single api call for each object which has to introduce some latency and cost. And put the metadata while call create_multipart_upload API. 
So it is better to add a soft-switch to on/off this feature, in most case it is not needed.
