### ISSUE TITLE
s3-migrate-serverless-s3migratejobsender 执行错误

### ISSUE THREAD

**Issue by JoeShi** [aws-samples/amazon-s3-resumable-upload#6]
我的理解是这个lambda是每小时执行一次，获取object list 并且更新DynamoDB Table. 

以下是错误信息
```
Job sqs queue is not empty or fail to get_queue_attributes. Stop process.
```

导致的现象是，新上传到 source S3中的文件没有传输到 dest S3.

**Comment by huangzbaws** [comment]
这个设计目的是为了满足这样的需求：
避免jobsender扫描S3桶的时候，上一次任务没有执行完，就提交了第二次的任务，这样上一次还没传输完的就会被再次扫描到，并且重新提交任务，导致重复任务。所以在Jobsender运行的时候，如果SQS 队列非空，则不予以执行。直到上一轮任务全部结束了，重新运行jobsender的时候会扫描到新出现的文件，并触发传输
