### ISSUE TITLE
Serverless version CN to Standard Partition failed

### ISSUE THREAD

**Issue by JoeShi** [aws-samples/amazon-s3-resumable-upload#8]
```
Version: Serverless
Source: AWS CN partiton
Dest: AWS Standard partiton
```
The cdk is deployed in AWS Standard partition. 

Error msg:
```
(AccessDenied) when calling the CreateMultipartUpload operation: Access Denied
(AccessDenied) when calling the PutObject operation: Access Denied
```

**Comment by huangzbaws** [comment]
In GET mode, should change the s3 access mode in cdk, to allow worker to write data to S3 bucket.

s3exist_bucket.grant_read_write(handler_jobsender)
s3exist_bucket.grant_read_write(handler)

**Comment by huangzbaws** [comment]
Commited
